# Generated by Django 3.1.7 on 2023-03-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0002_auto_20230319_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetmodel',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='datasetmodel',
            name='rows',
        ),
    ]
